def dockerImage
pipeline {
	agent any
	environment {
		CREDENTIALS_ID = 'dh_proj'
		DOCKER_FILE = '/home/jenkins/workspace/product_page/Dockerfile'
		IMAGE_NAME = 'productpage'
		REPO = 'taliadh/cicd_proj'
		VERSION = 'someversion'
	}
	stages {
		stage('Build'){
			steps {
				script {
					//Build the docker images
					sh 'pwd'
					sh "docker build -f ${DOCKER_FILE} --target build --tag ${IMAGE_NAME}:${VERSION}-build ."
				}	

			}
		}

		stage('Test') {
			steps {
				script {
					// Test
					sh "docker build -f ${DOCKER_FILE} --target test --tag ${IMAGE_NAME}:${VERSION}-test ."
					sh "docker run --rm ${IMAGE_NAME}:${VERSION}-test"
				}
			}
		}
		
		stage('Push') {
			steps {
				script {

					withCredentials([[$class: 'UsernamePasswordMultiBinding', credentialsId:"${CREDENTIALS_ID}", usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD']]) {
						sh "docker build -f ${DOCKER_FILE} --target run --tag ${IMAGE_NAME}:${VERSION}-stage ."
						sh "docker login -u $USERNAME -p $PASSWORD"
						sh "docker push ${IMAGE_NAME}:${VERSION}-stage"
					}				
				}	
			}
                }
	}
}

