pipeline {
    agent any
    environment {
        CREDENTIALS_ID = 'dh_proj'
        DOCKER_FILE = 'Dockerfile'
        IMAGE_NAME = 'productpage'
        REPO = 'taliadh'
        VERSION = "ver${env.BUILD_NUMBER}"
        WORK_DIR = "welcome/app/bookinfo/src/${IMAGE_NAME}/"
    }
    stages {
        stage('Build'){
            steps {
                script {
                    sh "docker build -f ${WORK_DIR}${DOCKER_FILE} --target build --tag ${IMAGE_NAME}:${VERSION}-build ${WORK_DIR}"
                }    
            }
        }
        stage('Test') {
            steps {
                script {
                    sh '''
                    docker build -f ${WORK_DIR}${DOCKER_FILE} --target test --tag ${IMAGE_NAME}:${VERSION}-test ${WORK_DIR}
                    docker run --rm ${IMAGE_NAME}:${VERSION}-test
                    '''
                }
            }
        }
        stage('Run') {
            steps {
                script {
                    sh "docker build -f ${WORK_DIR}${DOCKER_FILE} --target run --tag ${REPO}/${IMAGE_NAME}:${VERSION} ${WORK_DIR}"
                }
            }
        }
        stage('Push') {
            steps {
                script {
                    docker.withRegistry("", "${CREDENTIALS_ID}") {
                        sh '''
                        docker tag ${REPO}/${IMAGE_NAME}:${VERSION} ${REPO}/${IMAGE_NAME}:latest
                        docker push ${REPO}/${IMAGE_NAME}:${VERSION}
                        docker push ${REPO}/${IMAGE_NAME}:latest
                        '''
                    }
                }
            }
        }
    }
    post {
        success {
            echo 'All docker stages completed successfully!'
        }
        failure {
            echo 'Oops; Something went wrong :/'
        }
    }
}
