def dockerImage
pipeline {
	agent any
	environment {
		CREDENTIALS_ID = 'dh_proj'
                WORKDIR = 'welcome/app/bookinfo/src/productpage/'
		DOCKER_FILE = 'Dockerfile'
		IMAGE_NAME = 'productpage'
		REPO = 'taliadh'
                REPO_IMAGE = "${REPO}/${IMAGE_NAME}"
		VERSION = 'someversion'
	}
	stages {
		stage('Build'){
			steps {
				script {
					//Build the docker images
					sh "docker build -f ${WORKDIR}${DOCKER_FILE} --target build --tag ${IMAGE_NAME}:${VERSION}-build ${WORKDIR}"
				}	

			}
		}

		stage('Test') {
			steps {
				script {
					// Test
                                        sh '''
					docker build -f ${WORKDIR}${DOCKER_FILE} --target test --tag ${IMAGE_NAME}:${VERSION}-test ${WORKDIR}
					docker run --rm ${IMAGE_NAME}:${VERSION}-test
                                        '''
				}
			}
		}
		
		stage('Push') {
			steps {
				script {

                                        docker.withRegistry("https://index.docker.io/v1", "${CREDENTIALS_ID}") {
                                                sh '''
						docker build -f ${WORKDIR}${DOCKER_FILE} --target run --tag ${REPO_IMAGE}:${VERSION}-stage ${WORKDIR}
                                                docker tag ${REPO_IMAGE}:${VERSION}-stage ${REPO_IMAGE}:latest
						docker push ${REPO_IMAGE}:latest
                                                '''
					}				
				}	
			}
                }
	}
}

